[package]
name = "numeric-algebras-core"
version = "0.1.0"
edition = "2021"

[dependencies]
macrospace = {path = "../../macrospace"}

syn = {version = "2.0", features = ["fold"]}
quote = {version = "1.0"}
syn_derive = {version = "0.1"}
proc-macro2 = {version = "1.0"}
itertools = {version = "0.12"}
